# Generated by Django 3.2.25 on 2025-01-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_auto_20250121_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classes_per_week',
            field=models.IntegerField(default=3),
        ),
    ]
