# Generated by Django 3.2.25 on 2025-01-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0004_alter_course_classes_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classes_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
