# Generated by Django 3.2.25 on 2025-01-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0006_alter_course_classes_per_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='num_class_in_week',
        ),
    ]
