# Generated by Django 3.2.25 on 2025-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0007_remove_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='non_meeting_times',
            field=models.ManyToManyField(blank=True, related_name='unavailable_for_sections', to='SchedulerApp.MeetingTime'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 9:00', '8:00 - 9:00'), ('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='11:00 - 12:00', max_length=50),
        ),
    ]
