# Generated by Django 3.2.25 on 2025-02-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0008_auto_20250128_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture Room'), ('lab', 'Lab Room')], default='Lecture', max_length=10),
        ),
    ]
