# Generated by Django 3.2.25 on 2025-02-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0009_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture Room'), ('lab', 'Lab Room')], default='lecture', max_length=10),
        ),
    ]
