# Generated by Django 3.2.25 on 2025-02-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0010_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
